// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04lvyefSef8rM9_vdfEqsrax8f4TKm4o',
    appId: '1:537997958132:web:3d11374e1a4681211837a1',
    messagingSenderId: '537997958132',
    projectId: 'anonchat-poc',
    authDomain: 'anonchat-poc.firebaseapp.com',
    storageBucket: 'anonchat-poc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBKpeZ3r8xb1y1Wc016Tk2NDLHWhHdZs',
    appId: '1:537997958132:android:b427ac8fe45c8fa31837a1',
    messagingSenderId: '537997958132',
    projectId: 'anonchat-poc',
    storageBucket: 'anonchat-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARhSoNBdlGlxsa2C3GX9p84KE6CUROzwc',
    appId: '1:537997958132:ios:b62784852c37f7941837a1',
    messagingSenderId: '537997958132',
    projectId: 'anonchat-poc',
    storageBucket: 'anonchat-poc.appspot.com',
    iosBundleId: 'com.example.poc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARhSoNBdlGlxsa2C3GX9p84KE6CUROzwc',
    appId: '1:537997958132:ios:d4de2a2158e418c31837a1',
    messagingSenderId: '537997958132',
    projectId: 'anonchat-poc',
    storageBucket: 'anonchat-poc.appspot.com',
    iosBundleId: 'com.example.poc.RunnerTests',
  );
}
